# OWASP Dependency-Check
      - name: Install OWASP Dependency-Check
        run: |
          # Download the Dependency-Check ZIP file (use the latest available version)
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v11.1.1/dependency-check-11.1.1-release.zip

          # Check if the file was downloaded successfully (use the correct file name)
          if [ ! -f dependency-check-11.1.1-release.zip ]; then
            echo "Error: Dependency-Check zip file download failed!"
            exit 1
          fi

          # Verify the downloaded file size (ensure it's not empty)
          file_size=$(stat -c %s dependency-check-11.1.1-release.zip)
          if [ "$file_size" -le 0 ]; then
            echo "Error: The downloaded file is empty!"
            exit 1
          fi

          # Ensure the file is a valid zip file
          if ! unzip -t dependency-check-11.1.1-release.zip; then
            echo "Error: Invalid zip file."
            exit 1
          fi

          # Unzip the file
          unzip dependency-check-11.1.1-release.zip

          # List the contents of the unzip directory to check the structure
          ls -al

          # Check if the extracted folder exists
          if [ ! -d "dependency-check" ]; then
            echo "Error: dependency-check directory not found!"
            exit 1
          fi

          # Navigate to the correct directory
          cd dependency-check

          # Check the version of Dependency-Check
          ./bin/dependency-check.sh --version

      - name: Run OWASP Dependency-Check
        run: |
          # Ensure the script is in the correct directory after unzip
          cd dependency-check

          # Run Dependency-Check to scan the project and generate the report
          ./bin/dependency-check.sh --project "NodeJS App" --scan . --out ./dependency-check-report
